### ISSUE TITLE
consider w3m filters

### ISSUE THREAD

**Issue by Boruch-Baum** [sanel/declutter#1]
I saw your MELPA submission and took a look here. FYI, the [emacs-w3m project](https://github.com/emacs-w3m/emacs-w3m), also available on MELPA, has a feature called 'filters' that allows for HTML post-processing based upon URL regular expression. Filtering can be easily switched on/off universally (keybinding `f`) or on an individual basis (keybinding `C-u f`). See for example how it makes github.com URLS or slashdot.com URLS easier to view and navigate. The project makes it easy to create one's own personal filters, and we're a friendly group, so pull-requests are always welcome.

**Comment by sanel** [comment]
Thanks for the tip! But, I'm kind of confused what is idea behind this issue report :)

**Comment by Boruch-Baum** [comment]
On 2021-09-13 06:35, Sanel Z. wrote:
>    Thanks for the tip! But, I'm kind of confused what is idea behind this
>    issue report :)

Good news: No, you aren't confused at all. The "idea" *was* the tip. Enjoy.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by sanel** [comment]
Got it! :) I assume you referred to this [1] and they seems very
powerful. But, this is how declutter currently works:

```
site -> engine [eww|rdrview|lynx] -> simplified html -> shr.el (Emacs)
```

Most of the work is done by "engines", so Emacs will display only
simplified html.

I'll keep in mind this proposal to add filtering capability in the
future.

Thanks!

[1] https://github.com/emacs-w3m/emacs-w3m/blob/master/w3m-filter.el
