### ISSUE TITLE
can declutter support cjk character

### ISSUE THREAD

**Issue by emacs25** [sanel/declutter#2]
thanks for the amazing function

but it requires emacs25 which is very sad for me

can it be used for older version of emacs yet? 

i am using emacs23 on iPad and use lynx to browse web from terminal

lynx can enable cjk mode in options, so I wonder is it possible to show cjk character with declutter using emacs coding system

**Comment by sanel** [comment]
Thanks for your report. Can you try it with older Emacs versions? It doesn't use anything Emacs-version specific, except `shr.el` and `json.el`, but `json.el` is used only for outline.com parsing.

> lynx can enable cjk mode in options, so I wonder is it possible to show cjk character with declutter using emacs coding system

declutter will call lynx as is, without any specific options, so if you have cjk mode enabled by default, it should be shown. Also, it is assumed Emacs can show cjk as well.

Let me know how it goes.

**Comment by emacs25** [comment]
I have a try to start declutter

```
(require 'declutter) 
(setq declutter-engine 'lynx) 
```

first I remove the requirement of shr, json and eww by default, then I still got error:

can not open load file: shr

i search for shr within declutter and find a few result, so maybe that's the reason

**Comment by sanel** [comment]
Yes, `shr` is used for rendering and can't be removed. After I noticed
this [1], looks like shr (and eww) should be present in Emacs 25.

So, I'd suggest just to comment `json` requirement and try with that.

[1] https://emacs.stackexchange.com/a/5385

**Comment by emacs25** [comment]
sorry I can't understand what you said

the link shows that eww and shr can not be used for emacs23 manually

so what's the meaning of commenting json?

**Comment by sanel** [comment]
Oh sorry, I replied via email and wrongly assumed we are talking about
Emacs 25, without checking previous comments.

Sadly, Emacs 25 is a minimal version requirement, because declutter is
using shr.el and getting similar functionality without shr.el would be
very hard.

**Comment by emacs25** [comment]
got it, maybe the issue should be closed anyway

and thanks for your help
